[04-Apr-2016 12:57:08] ERROR [django.request:284] Internal Server Error: /polls/api/v1/questions/26/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.4/dist-packages/django/middleware/clickjacking.py", line 31, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'bool' object has no attribute 'get'
[04-Apr-2016 13:03:05] DEBUG [django.db.backends:89] (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
[04-Apr-2016 13:03:05] DEBUG [django.db.backends:89] (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
[04-Apr-2016 13:03:05] DEBUG [django.db.backends:89] (0.000) SHOW FULL TABLES; args=None
[04-Apr-2016 13:03:05] DEBUG [django.db.backends:89] (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
